In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import yfinance as yf

In [3]:
aapl= yf.download('AAPL', start='2014-01-01', end='2026-02-28')
nifty50 = yf.download('^NSEI', start='2014-01-01', end='2026-02-28')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [7]:
aapl.columns= aapl.columns.droplevel(1)
nifty50.columns= nifty50.columns.droplevel(1)

In [8]:
aapl.head()

Price       Date      Close       High        Low       Open     Volume
0     2014-01-02  17.140657  17.261513  17.106261  17.219679  234684800
1     2014-01-03  16.764153  17.158325  16.747108  17.132296  392467600
2     2014-01-06  16.855568  16.944504  16.535457  16.654763  412610800
3     2014-01-07  16.735027  16.918478  16.669332  16.867658  317209200
4     2014-01-08  16.841002  16.906076  16.693187  16.696904  258529600

In [9]:
nifty50.head()

Price       Date        Close         High          Low         Open  Volume
0     2014-01-02  6221.149902  6358.299805  6211.299805  6301.250000  158100
1     2014-01-03  6211.149902  6221.700195  6171.250000  6194.549805  139000
2     2014-01-06  6191.450195  6224.700195  6170.250000  6220.850098  118300
3     2014-01-07  6162.250000  6221.500000  6144.750000  6203.899902  138600
4     2014-01-08  6174.600098  6192.100098  6160.350098  6178.049805  146900

In [11]:
aapl.to_csv('../data/aapl_data.csv')
nifty50.to_csv('../data/nifty50_data.csv')